version: "3.7"

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: .
      target: base
    volumes:
      - ./:/app/
    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PYTHONUNBUFFERED
      - DEBUG
      - PORT
      - DB_ECHO_LOG=True
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  tests:
    container_name: tests
    build:
      context: .
      target: dev
    volumes:
      - ./:/app/
    command: ["pytest"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PYTHONUNBUFFERED
      - DEBUG
      - PORT
    depends_on:
      - postgres

volumes:
  postgresql_data:
